//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCP.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class copia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public copia()
        {
            this.registro_copias = new HashSet<registro_copias>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public int punto_copia_id { get; set; }
        public string codigo { get; set; }
        public int tipo_pago_id { get; set; }
        public System.DateTime fecha { get; set; }
        public double monto_sistema { get; set; }
        public double monto_real { get; set; }
        public int id_cliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual copia_puntos copia_puntos { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual tipos_pago tipos_pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registro_copias> registro_copias { get; set; }
    }
}
