//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCP.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class media_paises
    {
        public media_paises()
        {
        }

        public media_paises(int pais_id, int media_fi_id)
        {
            this.pais_id = pais_id;
            this.media_fi_id = media_fi_id;
        }

        public int id { get; set; }
        public int pais_id { get; set; }
        public int media_fi_id { get; set; }
    
        public virtual media_files media_files { get; set; }
        public virtual pais pais { get; set; }
    }
}
