//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCP.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class media_generos
    {
        public media_generos()
        {
        }

        public media_generos(int genero_id, int media_id)
        {
            this.genero_id = genero_id;
            this.media_id = media_id;
        }

        public int id { get; set; }
        public int genero_id { get; set; }
        public int media_id { get; set; }
    
        public virtual genero genero { get; set; }
        public virtual media_files media_files { get; set; }

        public override string ToString()
        {
            return genero.ToString();
        }
    }
}
