//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCP.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class media_managerEntities : DbContext
    {
        public media_managerEntities()
            : base("name=media_managerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<coeficientes_pago> coeficientes_pago { get; set; }
        public virtual DbSet<copia_puntos> copia_puntos { get; set; }
        public virtual DbSet<copia> copias { get; set; }
        public virtual DbSet<genero> generos { get; set; }
        public virtual DbSet<media_files> media_files { get; set; }
        public virtual DbSet<media_generos> media_generos { get; set; }
        public virtual DbSet<media_paises> media_paises { get; set; }
        public virtual DbSet<pais> paises { get; set; }
        public virtual DbSet<preferencia> preferencias { get; set; }
        public virtual DbSet<registro_copias> registro_copias { get; set; }
        public virtual DbSet<tipo_categorias> tipo_categorias { get; set; }
        public virtual DbSet<tipos_pago> tipos_pago { get; set; }
        public virtual DbSet<trabajadore> trabajadores { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
