//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCP.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class preferencia
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string valor_string { get; set; }
        public Nullable<int> valor_int { get; set; }
        public Nullable<double> valor_double { get; set; }
    }
}
