//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCP.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class usb
    {
        public int id_usb { get; set; }
        public string numero_serie { get; set; }
        public float capacidad { get; set; }
        public string marca { get; set; }
        public int id_cliente { get; set; }
    
        public virtual cliente cliente { get; set; }
    }
}
